#!/bin/bash 
  
cd
rm -rf ccminer
git clone https://github.com/saengx/ccminer 
cd /data/data/com.termux/files/usr/etc/miner/set-miner
cp -r online.json offline.json /data/data/com.termux/files/home/ccminer/miner/set-miner
cd
cd /data/data/com.termux/files/usr/etc/miner/setip
cp -r ip.json /data/data/com.termux/files/home/ccminer/miner/setip
cd
cd /data/data/com.termux/files/usr/etc
rm -rf miner 
cd
cd /data/data/com.termux/files/usr/bin
rm -rf add-file edit-miner run-miner restore backup
cd
cd ccminer 
chmod +x setup.sh setupdate.sh
sh setupdate.sh
